pipeline:
  build:
    image: g3rv4/transifex-builder
    commands:
      - "git clone git@github.com:g3rv4-docker/transifex.git output-image"
      - "rm -rf output-image/app/backend"
      - "mkdir -p output-image/app/backend"
      - "dotnet publish -f netcoreapp2.0 -o output-image/app/backend"
      - "cd output-image"
      - "git add app/backend"
      - "git commit -m 'Backend update: ${DRONE_COMMIT_SHA} - ${DRONE_COMMIT_MESSAGE}'"
      - "git push"